### ISSUE TITLE
Sum range with list error

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_skeleton#3]
Hello compas_skeleton developers,

This here pops up a message for me, it is not really possible to sum a range and a list.

I solved locally by:

`keys = list(range(1, 5)) + [1]`

https://github.com/BlockResearchGroup/compas_skeleton/blob/a30fd2d41f12a3891a578fa9c493333f7aeeb4a8/src/compas_skeleton/datastructure/skeleton.py#L240

Can we incorporate this, please?

Thanks
Ricardo

**Comment by ricardoavelino** [comment]
@wenqian157 help us please :)

**Comment by brgcode** [comment]
this will indeed no longer work in python 3+ (so it will only work when used in Rhino)...

**Comment by wenqian157** [comment]
updated it to the way you are using. ty ^^
